baseURL = 'https://yamatrail.com/'
languageCode = 'zh-tw'
title = "Yama's Trail"
theme = 'PaperMod'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
  identifier = "dev-log"
  name = "這個網站的誕生"
  url = "/dev-log/"
  weight = 1

[[menu.main]]
  identifier = "leetcode"
  name = "LeetCode 解題"
  url = "/leetcode/"
  weight = 2

[[menu.main]]
  identifier = "xv6"
  name = "xv6 學習紀錄"
  url = "/xv6/"
  weight = 3

[params]
  mainSections = ["posts", "k8s", "dev-log", "leetcode", "xv6"]
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  [params.assets]
    favicon = "/favicon_io/favicon.ico"
    favicon16x16 = "/favicon_io/favicon-16x16.png"
    favicon32x32 = "/favicon_io/favicon-32x32.png"
    apple_touch_icon = "/favicon_io/apple-touch-icon.png"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # 啟用 HTML 解析
